apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: million-real-estate-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: jsburbano07/million-real-estate-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: MONGO__URI
          value: "mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority"
        - name: MONGO__DATABASE
          value: "million"
        - name: JWT__SECRET
          value: "your-jwt-secret-key-here"
        - name: JWT__ISSUER
          value: "million-api"
        - name: JWT__AUDIENCE
          value: "million-frontend"
        - name: RATE_LIMITING__MAX_REQUESTS
          value: "100"
        - name: RATE_LIMITING__WINDOW_MINUTES
          value: "1"
        - name: LOG_LEVEL__DEFAULT
          value: "Information"
        - name: LOG_LEVEL__MICROSOFT_ASPNETCORE
          value: "Warning"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      scaling:
        minScale: 0
        maxScale: 10
