version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: million-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: million
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - million-network

  # Mongo Express (UI para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: million-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - million-network

  # Million Real Estate API
  million-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: million-api
    restart: unless-stopped
    environment:
      # Environment
      - ASPNETCORE_ENVIRONMENT=Production
      
      # MongoDB Configuration
      - MONGO_URI=mongodb://admin:password123@mongodb:27017
      - MONGO_DB=million
      
      # CORS
      - CORS_ORIGINS=http://localhost:3000,https://yourdomain.com
      
      # Rate Limiting
      - RATE_LIMIT_PERMINUTE=120
      - RATE_LIMIT_BURST=200
      - RATE_LIMIT_ENABLE_BURST=true
      
      # Logging
      - LOG_LEVEL=Information
      
      # Vercel Blob (configurar con tus tokens reales)
      - BLOB_READ_WRITE_TOKEN=your_vercel_blob_token_here
      
      # Media Limits
      - FEATURED_MEDIA_LIMIT=12
      - MEDIA_LIBRARY_LIMIT=60
      - MAX_UPLOAD_MB=25
      - ENABLE_VIDEO=false
      
      # JWT Configuration (generar claves reales para producción)
      - AUTH_JWT_ISSUER=https://yourdomain.com
      - AUTH_JWT_AUDIENCE=https://yourdomain.com
      - AUTH_JWT_PRIVATE_KEY=your_private_key_here
      - AUTH_JWT_PUBLIC_KEY=your_public_key_here
      - AUTH_ACCESS_TTL_MIN=10
      - AUTH_REFRESH_TTL_DAYS=14
      - AUTH_LOCKOUT_ATTEMPTS=5
      - AUTH_LOCKOUT_WINDOW_MIN=15
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - mongodb
    networks:
      - million-network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:

networks:
  million-network:
    driver: bridge

