version: '3.8'

services:
  # Million Real Estate API (desde GCR)
  million-api:
    image: gcr.io/${GCP_PROJECT_ID}/million-real-estate-api:latest
    container_name: million-api-gcp
    restart: unless-stopped
    environment:
      # Environment
      - ASPNETCORE_ENVIRONMENT=Production
      
      # MongoDB Atlas Configuration (configurar con tu connection string)
      - MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/million?retryWrites=true&w=majority
      - MONGO_DB=million
      
      # CORS (configurar con tu dominio)
      - CORS_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
      
      # Rate Limiting
      - RATE_LIMIT_PERMINUTE=120
      - RATE_LIMIT_BURST=200
      - RATE_LIMIT_ENABLE_BURST=true
      
      # Logging
      - LOG_LEVEL=Information
      
      # Vercel Blob (configurar con tus tokens reales)
      - BLOB_READ_WRITE_TOKEN=your_vercel_blob_token_here
      
      # Media Limits
      - FEATURED_MEDIA_LIMIT=12
      - MEDIA_LIBRARY_LIMIT=60
      - MAX_UPLOAD_MB=25
      - ENABLE_VIDEO=false
      
      # JWT Configuration (generar claves reales para producción)
      - AUTH_JWT_ISSUER=https://yourdomain.com
      - AUTH_JWT_AUDIENCE=https://yourdomain.com
      - AUTH_JWT_PRIVATE_KEY=your_private_key_here
      - AUTH_JWT_PUBLIC_KEY=your_public_key_here
      - AUTH_ACCESS_TTL_MIN=10
      - AUTH_REFRESH_TTL_DAYS=14
      - AUTH_LOCKOUT_ATTEMPTS=5
      - AUTH_LOCKOUT_WINDOW_MIN=15
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - million-network
    volumes:
      - ./logs:/app/logs

networks:
  million-network:
    driver: bridge


