version: "3.9"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express:1
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
  api:
    build:
      context: ..
      dockerfile: src/Million.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=million
      - CORS_ORIGINS=http://localhost:3000
      - RATE_LIMIT_PERMINUTE=120
      - LOG_LEVEL=Information
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
volumes:
  mongo_data:

